### ISSUE TITLE
Crash with Advanced Item Tab

### ISSUE THREAD

**Issue by HowardZHY** [HowardZHY/TooManyItems#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CustomSkinLoader (CustomSkinLoader_ForgeLegacy-14.15.jar)
  InputFix (InputFix-1.8.x-v2.jar)
  EFFLL (LiteLoader ObjectHolder fix) (ExtraFoamForLiteLoader-1.0.0.jar)
  ModTweaker (Patcher-1.8.5 (1.8.9).jar)
  NoBeaconBeam (nobeam-1.8.9.jar)
  TMIForgeLoader (!TMI-1.8.9-mixin.jar)
  BetterfpsdistMod (betterfpsdistance-1.8.9.jar)
  PatcherTweaker (Patcher-1.8.5 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 16/01/23 上午 12:59
XRay version: 47
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.minecraft.client.gui.inventory.GuiContainer.handler$zzb000$onInit(GuiContainer.java:786)
	at net.minecraft.client.gui.inventory.GuiContainer.<init>(GuiContainer.java:60)
	at net.minecraft.client.renderer.InventoryEffectRenderer.<init>(InventoryEffectRenderer.java:19)
	at net.minecraft.client.gui.inventory.GuiInventory.<init>(SourceFile:18)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1983)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.run(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.NullPointerException
	at fr.atesab.act.AdvancedItem.getSubItems(AdvancedItem.java:48)
	at net.minecraft.src.TMIGame.gameItems(TMIGame.java:206)
	at net.minecraft.src.TMIGame.allItems(TMIGame.java:214)
	at net.minecraft.src.TMIItemsPanel.<init>(TMIItemsPanel.java:17)
	at net.minecraft.src.TMISidebar.<init>(TMISidebar.java:6)
	at net.minecraft.src.TMIController.<init>(TMIController.java:22)
	at net.minecraft.src.TMI.<init>(TMI.java:5)
	at net.minecraft.src.TMI.<clinit>(TMI.java:4)
	... 20 more

**Comment by HowardZHY** [comment]
https://github.com/ate47/AdvancedCreativeTab/issues/18#issuecomment-1384153130
